import type { Category, Grade } from '@/domain'

/** 五年级：抽象思维与逻辑表达快速成长的一站 */
export const grade: Grade = {
  id: 'grade-5',
  name: '五年级',
  stage: 'primary',
  order: 6,
  ageRange: '10-11 岁',
  emoji: '🌏',
  tone: 'think',
  tagline: '学会推理和表达',
  summary: '抽象思维快速发展：分数与方程启蒙、文言文启蒙、算法与 AI 启蒙同时出现，学习更强调逻辑推理、方法总结与综合运用。',
  nextHint: '六年级要用知识解决真实问题，还能做自己的小项目！',
}

/** 五年级的七个学习领域：语文 / 数学 / 英语 / 科学 / 信息科技 / 艺术 / 劳动 */
export const categories: Category[] = [
  {
    id: 'grade-5-chinese',
    gradeId: 'grade-5',
    name: '语文',
    emoji: '📖',
    tone: 'language',
    summary: '阅读理解走向深度分析，古诗词与文言文启蒙同步推进，说明文、记叙文写作与口语表达要求更完整的结构。',
    focus: ['深度阅读理解', '古诗词与文言启蒙', '文体写作与表达'],
    skills: ['阅读理解', '古诗词', '文言文启蒙', '写作', '说明文', '记叙文', '文学阅读', '口语表达'],
    order: 1,
  },
  {
    id: 'grade-5-math',
    gradeId: 'grade-5',
    name: '数学',
    emoji: '🔢',
    tone: 'math',
    summary: '小数与分数运算全面展开，加入百分数与方程启蒙，几何从面积走到体积，统计与应用题强调建模与推理。',
    focus: ['分数小数与百分数', '方程与几何测量', '统计与数学推理'],
    skills: ['小数', '分数', '百分数启蒙', '方程启蒙', '几何', '面积', '体积', '统计', '应用题', '数学思维'],
    order: 2,
  },
  {
    id: 'grade-5-english',
    gradeId: 'grade-5',
    name: '英语',
    emoji: '🔤',
    tone: 'english',
    summary: '在词汇与语法的基础上加强篇章阅读与写作，让孩子能把听说读写综合起来完成真实的语言任务。',
    focus: ['词汇语法巩固', '篇章阅读与写作', '综合语言运用'],
    skills: ['词汇', '语法', '阅读', '听力', '口语', '写作', '综合语言运用'],
    order: 3,
  },
  {
    id: 'grade-5-science',
    gradeId: 'grade-5',
    name: '科学',
    emoji: '🔬',
    tone: 'science',
    summary: '把生物、物理与化学现象放进同一个探究框架，从地球走向宇宙，通过实验与探究理解变化背后的原因。',
    focus: ['跨领域科学概念', '实验设计与探究', '地球与宇宙视野'],
    skills: ['生物', '物理', '化学现象启蒙', '地球', '宇宙', '科学实验', '科学探究'],
    order: 4,
  },
  {
    id: 'grade-5-code',
    gradeId: 'grade-5',
    name: '信息科技',
    emoji: '💻',
    tone: 'code',
    summary: '从编程走向算法思维，理解数据与网络的运作方式，并借助 AI 启蒙和数字创作把技术用在自己的项目里。',
    focus: ['编程与算法思维', '数据与网络安全', 'AI 启蒙与数字创作'],
    skills: ['编程', '算法启蒙', '数据', '网络', '信息安全', '数字创作', 'AI启蒙'],
    order: 5,
  },
  {
    id: 'grade-5-art',
    gradeId: 'grade-5',
    name: '艺术',
    emoji: '🎨',
    tone: 'art',
    summary: '在音乐与美术的技能积累上提升审美判断，鼓励孩子用创意表达自己对生活与情感的观察。',
    focus: ['音乐与美术技能', '审美与艺术欣赏', '创意表达'],
    skills: ['音乐', '美术', '艺术欣赏', '创意表达'],
    order: 6,
  },
  {
    id: 'grade-5-labor',
    gradeId: 'grade-5',
    name: '劳动',
    emoji: '🛠️',
    tone: 'labor',
    summary: '把生活技能与家庭劳动变成稳定习惯，并能围绕一个实践项目规划步骤、使用工具、完成成果。',
    focus: ['生活技能自立', '家庭劳动分担', '实践项目完成'],
    skills: ['生活技能', '家庭劳动', '工具', '实践项目'],
    order: 7,
  },
]
