import type { Category, Grade } from '@/domain'

/** 大班：在游戏化学习之外加入幼小衔接，为上小学做准备。 */
export const grade: Grade = {
  id: 'preschool',
  name: '大班',
  stage: 'kindergarten',
  order: 1,
  ageRange: '5-6 岁',
  icon: 'plant',
  tone: 'think',
  tagline: '学拼音、认汉字，准备上小学',
  summary: '把语言、数学与科学探索继续加深，并用幼小衔接培养学习习惯与自我管理能力。',
  nextHint: '上了一年级，你会读课文、写生字，还会算加减法呢！',
}

/** 大班二级分类：7 个知识领域（含幼小衔接）。 */
export const categories: Category[] = [
  {
    id: 'preschool-language',
    gradeId: 'preschool',
    name: '语言与阅读',
    icon: 'speaker',
    tone: 'language',
    summary: '把中班的表达与阅读合在一起，从词语、句子走向有理解的倾听与讲述。',
    focus: ['完整表达', '理解故事', '词语与句子'],
    skills: ['朗诵', '儿歌', '故事', '古诗', '看图说话', '阅读理解', '词语', '句子', '语言表达', '绕口令'],
    order: 1,
  },
  {
    id: 'preschool-literacy',
    gradeId: 'preschool',
    name: '汉字与拼音启蒙',
    icon: 'chalkboard',
    tone: 'language',
    summary: '汉字与拼音同步启蒙，让孩子敢拼读、能认字、会组词。',
    focus: ['拼音拼读', '汉字结构', '组词运用'],
    skills: ['汉字', '偏旁', '部首', '组词', '拼音启蒙', '声母', '韵母', '拼读启蒙', '声调', '听音辨字'],
    order: 2,
  },
  {
    id: 'preschool-math',
    gradeId: 'preschool',
    name: '数学',
    icon: 'math-operations',
    tone: 'math',
    summary: '把数感扩展到 20 以内，并加入测量、时间与钱币等生活数学。',
    focus: ['20以内数感', '加减启蒙', '测量与时间'],
    skills: ['20以内数字', '数量关系', '加法启蒙', '减法启蒙', '比较', '排序', '分类', '图形', '测量', '时间', '钱币', '空间', '规律'],
    order: 3,
  },
  {
    id: 'preschool-science',
    gradeId: 'preschool',
    name: '科学探索',
    icon: 'flask',
    tone: 'science',
    summary: '从身边的动植物出发，一路问到人体、地球和太空。',
    focus: ['科学观察', '动手实验', '好奇心'],
    skills: ['动植物', '人体', '地球', '天气', '太空启蒙', '物理现象', '简单实验', '科学观察'],
    order: 4,
  },
  {
    id: 'preschool-art',
    gradeId: 'preschool',
    name: '艺术',
    icon: 'palette',
    tone: 'art',
    summary: '绘画、手工与音乐融合在一起，鼓励孩子大胆创意表达。',
    focus: ['色彩表达', '手工创意', '节奏感受'],
    skills: ['绘画', '色彩', '手工', '音乐', '节奏', '创意设计'],
    order: 5,
  },
  {
    id: 'preschool-think',
    gradeId: 'preschool',
    name: '思维训练',
    icon: 'brain',
    tone: 'think',
    summary: '在推理与规律游戏中提升记忆力、注意力和观察力。',
    focus: ['逻辑推理', '专注力', '记忆力'],
    skills: ['逻辑', '规律', '分类', '推理', '空间', '记忆', '注意力', '观察力'],
    order: 6,
  },
  {
    id: 'preschool-transition',
    gradeId: 'preschool',
    name: '幼小衔接',
    icon: 'backpack',
    tone: 'think',
    summary: '不做提前小学化，重点培养学习习惯、基础能力、学习兴趣与自我管理。',
    focus: ['学习习惯', '握笔与书写准备', '任务与时间管理'],
    skills: ['拼音启蒙', '识字', '数学基础', '握笔', '书写准备', '阅读习惯', '听课习惯', '任务完成', '注意力', '时间管理', '规则意识', '自主整理', '自主学习'],
    order: 7,
  },
]
