import type { Category, Grade } from '@/domain'

/** 二年级：在一年级基础上加深学科内容，并单独强化思维训练。 */
export const grade: Grade = {
  id: 'grade-2',
  name: '二年级',
  stage: 'primary',
  order: 3,
  ageRange: '7-8 岁',
  emoji: '🪐',
  tone: 'math',
  tagline: '我学会了乘法，还能写小故事',
  summary: '语文走向写话与阅读，数学进入乘法与数据，并加入信息科技和思维训练。',
  nextHint: '到了三年级，你会写作文、学分数，还会做科学小实验！',
}

/** 二年级二级分类：8 个学科领域。 */
export const categories: Category[] = [
  {
    id: 'grade-2-chinese',
    gradeId: 'grade-2',
    name: '语文',
    emoji: '📖',
    tone: 'language',
    summary: '积累词语与句子，读懂课文与古诗，从看图写话走向独立写话。',
    focus: ['词语句子', '阅读理解', '写话起步'],
    skills: ['汉字', '词语', '句子', '朗读', '课文', '古诗', '阅读理解', '看图写话', '写话', '口语表达'],
    order: 1,
  },
  {
    id: 'grade-2-math',
    gradeId: 'grade-2',
    name: '数学',
    emoji: '🔢',
    tone: 'math',
    summary: '在加减法之上学习表内乘法与除法启蒙，认识长度、时间与数据。',
    focus: ['表内乘法', '长度与时间', '应用题与数据'],
    skills: ['加减法', '乘法启蒙', '表内乘法', '除法启蒙', '长度', '时间', '图形', '数据', '应用题', '数学思维'],
    order: 2,
  },
  {
    id: 'grade-2-english',
    gradeId: 'grade-2',
    name: '英语',
    emoji: '🅰️',
    tone: 'english',
    summary: '积累词汇与句型，在听、说、读和情景表达中把英语用起来。',
    focus: ['词汇积累', '句型运用', '听说交流'],
    skills: ['词汇', '句型', '听力', '口语', '阅读', '情景表达'],
    order: 3,
  },
  {
    id: 'grade-2-science',
    gradeId: 'grade-2',
    name: '科学',
    emoji: '🔬',
    tone: 'science',
    summary: '认识动植物、材料、天气与地球，在实验和探究中学习提问与求证。',
    focus: ['科学观察', '动手实验', '探究提问'],
    skills: ['动植物', '材料', '天气', '地球', '简单实验', '科学探究'],
    order: 4,
  },
  {
    id: 'grade-2-moral',
    gradeId: 'grade-2',
    name: '道德与法治',
    emoji: '⚖️',
    tone: 'moral',
    summary: '从认识自我出发，理解家庭、学校与社会中的规则与责任。',
    focus: ['认识自我', '规则与责任', '社会认知'],
    skills: ['自我', '家庭', '学校', '社会', '规则', '责任'],
    order: 5,
  },
  {
    id: 'grade-2-art',
    gradeId: 'grade-2',
    name: '艺术',
    emoji: '🎨',
    tone: 'art',
    summary: '在音乐、美术与手工中欣赏美，也用创意表达自己的想法。',
    focus: ['音乐欣赏', '美术创作', '手工创意'],
    skills: ['音乐', '美术', '手工', '创意'],
    order: 6,
  },
  {
    id: 'grade-2-it',
    gradeId: 'grade-2',
    name: '信息科技',
    emoji: '💻',
    tone: 'code',
    summary: '认识信息与计算机，练习简单操作，并建立信息安全意识。',
    focus: ['信息认知', '简单操作', '信息安全'],
    skills: ['信息认知', '计算机', '简单操作', '信息安全启蒙'],
    order: 7,
  },
  {
    id: 'grade-2-think',
    gradeId: 'grade-2',
    name: '思维训练',
    emoji: '🧩',
    tone: 'think',
    summary: '用逻辑、推理与图形规律游戏提升观察力、记忆力和数学思维。',
    focus: ['逻辑推理', '图形规律', '观察与记忆'],
    skills: ['逻辑', '推理', '图形', '规律', '数学思维', '观察', '记忆'],
    order: 8,
  },
]
