import type { Category, Grade } from '@/domain'

/** 三年级：正式进入小学核心学科学习的一站 */
export const grade: Grade = {
  id: 'grade-3',
  name: '三年级',
  stage: 'primary',
  order: 4,
  ageRange: '8-9 岁',
  icon: 'globe',
  tone: 'explore',
  tagline: '学科世界正式打开',
  summary: '从识字朗读转向学科学习，语文、数学、英语、科学、道德与法治、艺术、信息科技与劳动同时起步，重点是建立稳定的学习习惯与扎实的基础概念。',
  nextHint: '四年级会遇见更大的数和更远的星空哦！',
}

/** 三年级的八个学习领域：语文 / 数学 / 英语 / 科学 / 道德与法治 / 艺术 / 信息科技 / 劳动 */
export const categories: Category[] = [
  {
    id: 'grade-3-chinese',
    gradeId: 'grade-3',
    name: '语文',
    icon: 'book',
    tone: 'language',
    summary: '在字词与课文的基础上，把阅读理解与书面表达连成一条线，让积累真正变成会用的语言能力。',
    focus: ['字词与语言积累', '朗读与阅读理解', '口语与习作表达'],
    skills: ['字词', '课文', '古诗', '阅读理解', '写作', '口语交际', '习作', '文学常识'],
    order: 1,
  },
  {
    id: 'grade-3-math',
    gradeId: 'grade-3',
    name: '数学',
    icon: 'math-operations',
    tone: 'math',
    summary: '把四则运算练到熟练，并用长度、周长、面积与图形建立空间感，让孩子学会用数学表达和解决生活问题。',
    focus: ['运算熟练与准确', '量与图形的概念', '解决问题的思路'],
    skills: ['四则运算', '乘除法', '分数启蒙', '小数启蒙', '面积', '长度', '周长', '图形', '应用题', '数学思维'],
    order: 2,
  },
  {
    id: 'grade-3-english',
    gradeId: 'grade-3',
    name: '英语',
    icon: 'translate',
    tone: 'english',
    summary: '以词汇和句型为主线，配合听、说、读、写的启蒙练习，帮助孩子敢开口、能听懂、读得懂简短语篇。',
    focus: ['词汇与句型积累', '听说习惯养成', '语法与读写启蒙'],
    skills: ['词汇', '句型', '语法启蒙', '听力', '口语', '阅读', '写作启蒙'],
    order: 3,
  },
  {
    id: 'grade-3-science',
    gradeId: 'grade-3',
    name: '科学',
    icon: 'flask',
    tone: 'science',
    summary: '从身边的生物、物质、能量、地球与天气出发，通过动手实验和科学探究，培养观察、提问与解释现象的能力。',
    focus: ['观察与提问', '动手实验', '解释自然现象'],
    skills: ['生物', '物质', '能量', '地球', '天气', '实验', '科学探究'],
    order: 4,
  },
  {
    id: 'grade-3-moral',
    gradeId: 'grade-3',
    name: '道德与法治',
    icon: 'scales',
    tone: 'moral',
    summary: '结合家庭、学校与公共生活，帮助孩子理解规则、承担责任，并逐步建立对自己与国家的认知。',
    focus: ['规则意识', '责任与担当', '公共生活参与'],
    skills: ['社会', '规则', '责任', '公共生活', '家庭', '国家认知'],
    order: 5,
  },
  {
    id: 'grade-3-art',
    gradeId: 'grade-3',
    name: '艺术',
    icon: 'palette',
    tone: 'art',
    summary: '在音乐与美术的实践中感受美、欣赏美，并鼓励孩子用自己的方式表达想法和情绪。',
    focus: ['音乐与美术基础', '艺术欣赏眼光', '创意表达'],
    skills: ['音乐', '美术', '艺术欣赏', '创意表达'],
    order: 6,
  },
  {
    id: 'grade-3-code',
    gradeId: 'grade-3',
    name: '信息科技',
    icon: 'code',
    tone: 'code',
    summary: '认识信息与网络的基本规则，从编程启蒙入手理解顺序与指令，同时建立数字安全意识。',
    focus: ['信息处理与表达', '网络使用基础', '编程启蒙与数字安全'],
    skills: ['信息处理', '互联网基础', '编程启蒙', '数字安全'],
    order: 7,
  },
  {
    id: 'grade-3-labor',
    gradeId: 'grade-3',
    name: '劳动',
    icon: 'wrench',
    tone: 'labor',
    summary: '从家务和整理自己的物品开始，认识常见工具并完成简单制作，让生活技能成为独立成长的第一步。',
    focus: ['家务参与', '整理与自理', '工具与简单制作'],
    skills: ['家务', '整理', '工具', '简单制作', '生活技能'],
    order: 8,
  },
]
