import type { Category, Grade } from '@/domain'

/** 四年级：从“学会”走向“会学”的一站 */
export const grade: Grade = {
  id: 'grade-4',
  name: '四年级',
  stage: 'primary',
  order: 5,
  ageRange: '9-10 岁',
  icon: 'compass',
  tone: 'science',
  tagline: '看现象，也看规律',
  summary: '阅读与写作要求明显提高，数学进入大数、小数与几何，科学扩展到物理现象与天文，学习开始从记忆结论转向理解方法。',
  nextHint: '五年级会遇到分数、百分数和宇宙的秘密，一起出发吧！',
}

/** 四年级的七个学习领域：语文 / 数学 / 英语 / 科学 / 信息科技 / 艺术 / 劳动 */
export const categories: Category[] = [
  {
    id: 'grade-4-chinese',
    gradeId: 'grade-4',
    name: '语文',
    icon: 'book',
    tone: 'language',
    summary: '在阅读中练习理解与概括，在古诗与文言启蒙中感受语言的典雅，并把词语、语法积累落到写作与口语交际上。',
    focus: ['阅读理解与概括', '古诗与文言启蒙', '写作与口语表达'],
    skills: ['阅读', '古诗', '文言启蒙', '写作', '词语', '语法', '口语交际', '文学阅读'],
    order: 1,
  },
  {
    id: 'grade-4-math',
    gradeId: 'grade-4',
    name: '数学',
    icon: 'math-operations',
    tone: 'math',
    summary: '认识更大的数，熟练小数与分数的初步运算，并借助角、面积与统计把几何和数据处理连成完整的数学图景。',
    focus: ['数的扩展与运算', '几何与测量', '统计与解决问题'],
    skills: ['大数', '四则运算', '小数', '分数', '几何', '角', '面积', '统计', '应用题', '数学思维'],
    order: 2,
  },
  {
    id: 'grade-4-english',
    gradeId: 'grade-4',
    name: '英语',
    icon: 'translate',
    tone: 'english',
    summary: '语法体系开始成形，配合阅读、听力、口语与写作的同步训练，让孩子能在真实情景中自然表达。',
    focus: ['词汇与语法体系', '听说读写同步', '情景中运用语言'],
    skills: ['词汇', '语法', '阅读', '听力', '口语', '写作', '情景表达'],
    order: 3,
  },
  {
    id: 'grade-4-science',
    gradeId: 'grade-4',
    name: '科学',
    icon: 'flask',
    tone: 'science',
    summary: '从生物与物理现象走向能量、地球与天文，通过实验记录与比较，培养用证据解释世界的科学态度。',
    focus: ['现象与规律', '实验与记录', '地球与天文视野'],
    skills: ['生物', '物理现象', '能量', '地球', '天文', '实验'],
    order: 4,
  },
  {
    id: 'grade-4-code',
    gradeId: 'grade-4',
    name: '信息科技',
    icon: 'code',
    tone: 'code',
    summary: '认识计算机与网络的工作原理，学会安全地使用信息和数据，并通过编程与数字创作把想法做成作品。',
    focus: ['计算机与网络认知', '数据与信息安全', '编程与数字创作'],
    skills: ['计算机', '网络', '信息安全', '数据', '编程', '数字创作'],
    order: 5,
  },
  {
    id: 'grade-4-art',
    gradeId: 'grade-4',
    name: '艺术',
    icon: 'palette',
    tone: 'art',
    summary: '在音乐与美术的表现手法上更进一步，学会欣赏经典作品，也能独立完成属于自己的创作。',
    focus: ['音乐与美术表现', '艺术欣赏', '独立创作'],
    skills: ['音乐', '美术', '艺术欣赏', '创作'],
    order: 6,
  },
  {
    id: 'grade-4-labor',
    gradeId: 'grade-4',
    name: '劳动',
    icon: 'wrench',
    tone: 'labor',
    summary: '承担固定的家庭劳动，规范使用常见工具，并围绕真实问题完成制作与实践任务。',
    focus: ['家庭劳动习惯', '工具规范使用', '动手制作与实践'],
    skills: ['家庭劳动', '工具使用', '制作', '实践'],
    order: 7,
  },
]
