import type { Category, Grade } from '@/domain'

/** 六年级：小学阶段的最后一站，重点转向综合运用与独立思考 */
export const grade: Grade = {
  id: 'grade-6',
  name: '六年级',
  stage: 'primary',
  order: 7,
  ageRange: '11-12 岁',
  emoji: '🏝️',
  tone: 'math',
  tagline: '把知识用起来',
  summary: '重点从“掌握知识”过渡到“理解知识 + 综合运用 + 独立思考”，在巩固小学核心能力的同时完成向初中的学习衔接与心态准备。',
  nextHint: '初中会认识物理、化学这些新朋友，还能做更酷的实验！',
}

/** 六年级的八个学习领域：语文 / 数学 / 英语 / 科学 / 信息科技 / 道德与法治 / 艺术 / 劳动 */
export const categories: Category[] = [
  {
    id: 'grade-6-chinese',
    gradeId: 'grade-6',
    name: '语文',
    emoji: '📖',
    tone: 'language',
    summary: '阅读拓展与古诗词、文言文积累并行，综合性学习把听说读写整合起来，让表达更有条理也更有思想。',
    focus: ['阅读拓展与文言积累', '综合性学习整合', '表达与写作提升'],
    skills: ['阅读理解', '古诗词', '文言文', '写作', '综合性学习', '文学阅读', '表达能力', '阅读拓展'],
    order: 1,
  },
  {
    id: 'grade-6-math',
    gradeId: 'grade-6',
    name: '数学',
    emoji: '🔢',
    tone: 'math',
    summary: '分数、百分数、比与比例构成完整的关系模型，圆与圆柱圆锥打通二维到三维，统计与综合实践强调真实问题中的数学建模。',
    focus: ['比例关系与建模', '立体图形与几何', '统计与综合实践'],
    skills: ['分数', '百分数', '比', '比例', '圆', '圆柱', '圆锥', '统计', '应用题', '数学思维', '综合实践'],
    order: 2,
  },
  {
    id: 'grade-6-english',
    gradeId: 'grade-6',
    name: '英语',
    emoji: '🔤',
    tone: 'english',
    summary: '语法体系梳理完整，听说读写围绕综合应用训练，为初中更长篇幅的语言学习做好准备。',
    focus: ['语法体系梳理', '听说读写综合', '为初中语言学习打底'],
    skills: ['词汇', '语法', '阅读', '听力', '口语', '写作', '综合应用'],
    order: 3,
  },
  {
    id: 'grade-6-science',
    gradeId: 'grade-6',
    name: '科学',
    emoji: '🔬',
    tone: 'science',
    summary: '生物、物理与化学启蒙共同搭建对物质世界的整体认识，配合地球、宇宙内容与实验探究，直接衔接初中理科。',
    focus: ['理科概念整体建构', '实验与探究能力', '衔接初中科学学习'],
    skills: ['生物', '物理', '化学启蒙', '地球', '宇宙', '科学实验', '科学探究'],
    order: 4,
  },
  {
    id: 'grade-6-code',
    gradeId: 'grade-6',
    name: '信息科技',
    emoji: '💻',
    tone: 'code',
    summary: '以编程与算法为核心，结合数据、网络与信息安全，并让孩子了解 AI 基础，学会把技术转化为解决问题的工具。',
    focus: ['编程与算法', '数据与网络素养', 'AI 基础与数字创作'],
    skills: ['编程', '算法', '数据', '网络', '信息安全', 'AI基础', '数字创作'],
    order: 5,
  },
  {
    id: 'grade-6-moral',
    gradeId: 'grade-6',
    name: '道德与法治',
    emoji: '🤝',
    tone: 'moral',
    summary: '在社会与公共生活中理解法治与责任，把个人成长放进国家与社会的视角中思考。',
    focus: ['法治观念', '责任与社会参与', '国家与公共生活认知'],
    skills: ['社会', '法治', '责任', '国家', '公共生活'],
    order: 6,
  },
  {
    id: 'grade-6-art',
    gradeId: 'grade-6',
    name: '艺术',
    emoji: '🎨',
    tone: 'art',
    summary: '在音乐与美术的长期浸泡中形成个人审美，能够欣赏作品并独立完成有想法的创作。',
    focus: ['音乐与美术素养', '艺术欣赏判断', '个人化创作'],
    skills: ['音乐', '美术', '艺术欣赏', '创作'],
    order: 7,
  },
  {
    id: 'grade-6-labor',
    gradeId: 'grade-6',
    name: '劳动',
    emoji: '🧺',
    tone: 'labor',
    summary: '把生活技能与实践经验整合成完整项目，从设计、制作到改进，体会劳动带来的独立与成就感。',
    focus: ['生活技能综合运用', '项目式实践', '制作与改进'],
    skills: ['生活技能', '实践', '制作', '综合劳动项目'],
    order: 8,
  },
]
