import type { Category, Grade } from '@/domain'

/** 中班：幼儿园阶段的第一站，以游戏、动手和表达为主。 */
export const grade: Grade = {
  id: 'nursery',
  name: '中班',
  stage: 'kindergarten',
  order: 0,
  ageRange: '4-5 岁',
  icon: 'acorn',
  tone: 'explore',
  tagline: '敢说敢画，爱问为什么',
  summary: '用绘本、游戏和动手操作陪孩子认识世界，重点培养语言表达、阅读兴趣与数学直觉。',
  nextHint: '到了大班，你会认识拼音，还能给汉字找朋友哦！',
}

/** 中班二级分类：12 个知识领域。 */
export const categories: Category[] = [
  {
    id: 'nursery-language',
    gradeId: 'nursery',
    name: '语言表达',
    icon: 'speaker',
    tone: 'language',
    summary: '让孩子敢说、愿意说、能够完整表达。',
    focus: ['敢说愿说', '完整表达', '倾听习惯'],
    skills: ['朗诵', '儿歌', '故事', '看图说话', '词语认知', '口语表达', '倾听训练', '绕口令', '古诗启蒙'],
    order: 1,
  },
  {
    id: 'nursery-reading',
    gradeId: 'nursery',
    name: '阅读启蒙',
    icon: 'book-open',
    tone: 'reading',
    summary: '从绘本与图片出发，养成安静翻书、读懂故事的习惯。',
    focus: ['阅读兴趣', '故事理解', '图文观察'],
    skills: ['绘本阅读', '图片阅读', '故事理解', '角色认知', '情节排序', '看图找信息', '简单阅读理解'],
    order: 2,
  },
  {
    id: 'nursery-literacy',
    gradeId: 'nursery',
    name: '识字启蒙',
    icon: 'pencil-ruler',
    tone: 'language',
    summary: '走“图片→汉字→声音→游戏→记忆”的路线，不一开始就机械抄写。',
    focus: ['汉字兴趣', '看图识字', '汉字配对'],
    skills: ['常见汉字', '象形字', '汉字认知', '看图识字', '汉字配对', '汉字找朋友', '简单组词'],
    order: 3,
  },
  {
    id: 'nursery-math',
    gradeId: 'nursery',
    name: '数学启蒙',
    icon: 'math-operations',
    tone: 'math',
    summary: '在生活与游戏里建立数感、图形感和简单的加减概念。',
    focus: ['数感建立', '比较与分类', '图形与规律'],
    skills: ['数字认知', '10以内数量', '数数', '大小比较', '多与少', '排序', '分类', '图形', '颜色', '规律', '空间方向', '简单加减概念'],
    order: 4,
  },
  {
    id: 'nursery-drawing',
    gradeId: 'nursery',
    name: '绘画',
    icon: 'palette',
    tone: 'art',
    summary: '用线条、形状和色彩自由表达看到和想到的世界。',
    focus: ['线条与形状', '色彩感受', '自由创作'],
    skills: ['线条', '形状', '涂色', '简单临摹', '创意绘画', '场景绘画', '动物绘画', '植物绘画', '自由创作'],
    order: 5,
  },
  {
    id: 'nursery-craft',
    gradeId: 'nursery',
    name: '手工',
    icon: 'scissors',
    tone: 'art',
    summary: '剪、折、贴、拼，在动手中锻炼小手和空间想象。',
    focus: ['小肌肉发展', '动手拼搭', '材料创意'],
    skills: ['剪纸', '折纸', '粘贴', '拼搭', '简单立体制作', '废旧材料创作'],
    order: 6,
  },
  {
    id: 'nursery-music',
    gradeId: 'nursery',
    name: '音乐',
    icon: 'music-notes',
    tone: 'music',
    summary: '在唱唱跳跳中感受节奏与音高，让耳朵先爱上音乐。',
    focus: ['节奏感', '音高感知', '音乐游戏'],
    skills: ['儿歌', '节奏', '音高感知', '模仿声音', '音乐游戏', '简单乐器认知'],
    order: 7,
  },
  {
    id: 'nursery-science',
    gradeId: 'nursery',
    name: '科学探索',
    icon: 'flask',
    tone: 'science',
    summary: '核心不是背知识，而是“观察→猜想→操作→发现”的探索过程。',
    focus: ['自然观察', '大胆猜想', '动手发现'],
    skills: ['动物', '植物', '天气', '四季', '水', '光', '声音', '磁铁', '身体', '自然观察'],
    order: 8,
  },
  {
    id: 'nursery-life',
    gradeId: 'nursery',
    name: '生活认知',
    icon: 'home',
    tone: 'life',
    summary: '认识自己的身体与日常生活，学会照顾自己和注意安全。',
    focus: ['认识自己', '生活常识', '安全意识'],
    skills: ['身体认知', '食物', '衣服', '家庭', '幼儿园', '交通工具', '安全', '时间', '日常生活'],
    order: 9,
  },
  {
    id: 'nursery-think',
    gradeId: 'nursery',
    name: '思维训练',
    icon: 'brain',
    tone: 'think',
    summary: '在找不同、迷宫和拼图里练出观察力和简单逻辑。',
    focus: ['观察力', '简单逻辑', '专注力'],
    skills: ['找不同', '分类', '配对', '排序', '规律', '迷宫', '拼图', '空间关系', '简单逻辑'],
    order: 10,
  },
  {
    id: 'nursery-social',
    gradeId: 'nursery',
    name: '社交表达',
    icon: 'handshake',
    tone: 'social',
    summary: '学习礼貌、分享与合作，也能说出自己的情绪和需求。',
    focus: ['礼貌分享', '情绪认知', '表达需求'],
    skills: ['礼貌用语', '分享', '合作', '情绪认知', '表达需求', '与朋友相处', '解决简单冲突'],
    order: 11,
  },
  {
    id: 'nursery-english',
    gradeId: 'nursery',
    name: '英语启蒙',
    icon: 'translate',
    tone: 'english',
    summary: '从字母、儿歌和身边的事物开始，先把英语当成好玩的声音。',
    focus: ['字母认读', '常见单词', '开口表达'],
    skills: ['字母', '常见单词', '动物', '颜色', '数字', '家庭', '食物', '日常表达', '英语儿歌'],
    order: 12,
  },
]
