import type { Topic } from '@/domain'

/**
 * 中班的学习主题。
 *
 * 目前只放“已经能玩”的示例主题；其余领域保持空数组，
 * 界面会自动显示“内容准备中 · 等待教案”——
 * 这正是“内容与 UI 解耦”的意义：补内容不需要动任何页面。
 */
export const topics: Topic[] = [
  {
    id: 'nursery-language-chunxiao',
    gradeId: 'nursery',
    categoryId: 'nursery-language',
    title: '《春晓》',
    icon: 'flower',
    kind: 'standard',
    order: 1,
    level: 1,
    objectives: [
      '愿意跟着读《春晓》，感受古诗的节奏',
      '知道诗里写了春天的早晨',
      '能说出“鸟”“花”“雨”这些词',
    ],
    knowledgePoints: [
      { id: 'kp-chunxiao-author', label: '《春晓》的作者孟浩然' },
      { id: 'kp-chunxiao-order', label: '《春晓》四句的顺序' },
      { id: 'kp-chunxiao-scene', label: '诗中写到的春天景物' },
    ],
    lessonIds: ['nursery-language-chunxiao-1'],
  },
  {
    id: 'nursery-language-chunxiao-challenge',
    gradeId: 'nursery',
    categoryId: 'nursery-language',
    title: '挑战：自己朗诵《春晓》',
    icon: 'microphone',
    kind: 'challenge',
    order: 2,
    level: 2,
    objectives: ['能完整地、有节奏地朗诵《春晓》', '愿意在别人面前大声朗读'],
    knowledgePoints: [{ id: 'kp-chunxiao-recite', label: '有节奏地朗诵古诗' }],
    lessonIds: [],
  },
  {
    id: 'nursery-language-secret',
    gradeId: 'nursery',
    categoryId: 'nursery-language',
    title: '古诗里的秘密花园',
    icon: 'key',
    kind: 'hidden',
    order: 3,
    level: 1,
    objectives: ['在熟悉的故事里发现新的小惊喜'],
    knowledgePoints: [{ id: 'kp-poem-secret', label: '古诗里的小细节' }],
    lessonIds: [],
  },
  {
    id: 'nursery-math-shapes',
    gradeId: 'nursery',
    categoryId: 'nursery-math',
    title: '图形宝宝找家',
    icon: 'shapes',
    kind: 'standard',
    order: 1,
    level: 1,
    objectives: ['能认出圆形、三角形、正方形', '能按形状分类', '愿意说出“它有几条边”'],
    knowledgePoints: [
      { id: 'kp-shape-circle', label: '圆形：没有角' },
      { id: 'kp-shape-triangle', label: '三角形：三条边' },
      { id: 'kp-shape-square', label: '正方形：四条一样长的边' },
      { id: 'kp-shape-sort', label: '按形状分类' },
    ],
    lessonIds: ['nursery-math-shapes-1'],
  },
  {
    id: 'nursery-science-ice',
    gradeId: 'nursery',
    categoryId: 'nursery-science',
    title: '冰去哪儿了？',
    icon: 'snowflake',
    kind: 'standard',
    order: 1,
    level: 1,
    objectives: ['愿意先猜再试', '知道冰遇热会化成水', '能说出自己看到的变化'],
    knowledgePoints: [
      { id: 'kp-ice-melt', label: '冰遇热会融化' },
      { id: 'kp-ice-water', label: '冰化成水，水还在' },
      { id: 'kp-ice-observe', label: '观察并说出变化' },
    ],
    lessonIds: ['nursery-science-ice-1'],
  },
  {
    id: 'nursery-language-measure-words',
    gradeId: 'nursery',
    categoryId: 'nursery-language',
    title: '量词小魔法师',
    icon: 'stamp',
    kind: 'standard',
    order: 4,
    level: 1,
    objectives: [
      '能给城堡、汽车这样的东西找到合适的量词',
      '会用量词说「一座城堡」「一辆汽车」',
      '愿意用量词把一样一样东西连起来说一遍',
    ],
    knowledgePoints: [
      { id: 'kp-measure-concept', label: '量词就是数东西时用的那个词', detail: '例如「一座城堡」里的「座」' },
      { id: 'kp-measure-building', label: '建筑物量词：座', detail: '一座城堡、一座桥' },
      { id: 'kp-measure-vehicle', label: '交通工具量词：辆 / 条 / 列 / 架', detail: '一辆汽车、一条马路、一列火车、一架飞机' },
      { id: 'kp-measure-nature', label: '大自然与植物量词：朵 / 片 / 棵', detail: '一朵云、一片叶子、一棵大树、一座山、一条河' },
      { id: 'kp-measure-food', label: '食物量词：片 / 块 / 根 / 个 / 串', detail: '一片面包、一块蛋糕、一根胡萝卜、一个苹果、一串葡萄' },
    ],
    lessonIds: ['nursery-language-measure-words-1'],
  },
  {
    id: 'nursery-language-measure-words-challenge',
    gradeId: 'nursery',
    categoryId: 'nursery-language',
    title: '挑战：量词开火车',
    icon: 'train',
    kind: 'challenge',
    order: 5,
    level: 2,
    objectives: ['能一连给好几样东西配上对的量词', '愿意用量词把一整句话说完'],
    knowledgePoints: [
      { id: 'kp-measure-concept', label: '量词就是数东西时用的那个词', detail: '例如「一座城堡」里的「座」' },
      { id: 'kp-measure-building', label: '建筑物量词：座', detail: '一座城堡、一座桥' },
      { id: 'kp-measure-vehicle', label: '交通工具量词：辆 / 条 / 列 / 架', detail: '一辆汽车、一条马路、一列火车、一架飞机' },
      { id: 'kp-measure-nature', label: '大自然与植物量词：朵 / 片 / 棵', detail: '一朵云、一片叶子、一棵大树、一座山、一条河' },
      { id: 'kp-measure-food', label: '食物量词：片 / 块 / 根 / 个 / 串', detail: '一片面包、一块蛋糕、一根胡萝卜、一个苹果、一串葡萄' },
    ],
    lessonIds: [],
  },
  {
    id: 'nursery-language-autumn-colors',
    gradeId: 'nursery',
    categoryId: 'nursery-language',
    title: '秋天的颜色',
    icon: 'leaf',
    kind: 'standard',
    order: 6,
    level: 1,
    objectives: [
      '知道秋天来了，小草、枫叶、菊花、稻谷的颜色都在变',
      '能说出「秋天是五彩缤纷的」',
      '愿意把表示颜色的词念重一点，把这首小诗念出来',
    ],
    knowledgePoints: [
      { id: 'kp-autumn-change', label: '秋天来了，身边的颜色会变', detail: '小草变黄、枫叶变红、菊花开了、稻谷金黄' },
      { id: 'kp-autumn-grass', label: '小草说：秋天是黄色的', detail: '小草的绿衣服慢慢变成了黄色' },
      { id: 'kp-autumn-maple', label: '枫叶说：秋天是红色的', detail: '枫叶红得像一团燃烧的小火苗' },
      { id: 'kp-autumn-chrysanthemum', label: '菊花说：秋天是彩色的', detail: '花瓣里藏着黄色、白色和紫色' },
      { id: 'kp-autumn-rice', label: '稻谷说：秋天是金色的', detail: '金黄的稻谷沉甸甸，笑弯了腰' },
      { id: 'kp-recital-pause', label: '念的时候在意群之间停一停', detail: '「秋天 / 是什么颜色？」不要一口气念完' },
      { id: 'kp-recital-stress', label: '把表示颜色的词念得重一点', detail: '黄色、红色、彩色、金色、五彩缤纷' },
    ],
    lessonIds: ['nursery-language-autumn-colors-1'],
  },
  {
    id: 'nursery-language-autumn-colors-challenge',
    gradeId: 'nursery',
    categoryId: 'nursery-language',
    title: '挑战：把秋天念给大家听',
    icon: 'microphone',
    kind: 'challenge',
    order: 7,
    level: 2,
    objectives: ['能把《秋天的颜色》完整地、有节奏地念出来', '愿意把颜色词念重一点，念给大家听'],
    knowledgePoints: [
      { id: 'kp-recital-pause', label: '念的时候在意群之间停一停', detail: '「秋天 / 是什么颜色？」不要一口气念完' },
      { id: 'kp-recital-stress', label: '把表示颜色的词念得重一点', detail: '黄色、红色、彩色、金色、五彩缤纷' },
    ],
    lessonIds: [],
  },
]
